module.exports.GenericSignal = require('./generic-signal.class.js')
module.exports.Constant = require('./constant.class.js')
module.exports.Step = require('./step.class.js')
module.exports.Ramp = require('./ramp.class.js')
module.exports.Sine = require('./sine.class.js')
module.exports.ExpSine = require('./exp-sine.class.js')
module.exports.Exponentials = require('./exponentials.class.js')